import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import 'aos/dist/aos.css'
import TranslationProvider from '@/providers/translate.provider'
import initTranslations from '@/i18n'
import i18nConfig from '@/next-i18next.config'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Uz Beans',
  description: 'Generated by create next app',
  icons: {
    icon: "/logo.png",
  },
}

export function generateStaticParams () {
  return i18nConfig.locales.map(locale => ({ locale }))
}

const i18nNamespaces = ['translation']

export default async function RootLayout ({
  children,
  params: { locale }
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const { resources } = await initTranslations(locale, i18nNamespaces)

  return (
    
    <html lang={locale}>
       <link rel="icon" href="/logo.png" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TranslationProvider
          locale={locale}
          resources={resources}
          namespaces={i18nNamespaces}
        >
          {children}
        </TranslationProvider>
      </body>
    </html>
  )
}
